[package]
name = "rust-crud-api"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = "0.19.9"
serde = "1.0.217"
serde_json = "1.0.134"
serde_derive = "1.0.217"
build = "0.0.2"

# Note: serde, necessary to implement the serialize and deserialize trait.
